AWSTemplateFormatVersion: '2010-09-09'
Description: 'Sysdig Response Actions Lambda Functions - Multi-Region Deployment'

Parameters:
  ResourceName:
    Type: String
    Description: Base name for all resources
  S3BucketPrefix:
    Type: String
    Description: Prefix for regional S3 buckets containing Lambda deployment packages (bucket name will be {prefix}-{region})
  ApiBaseUrl:
    Type: String
    Description: API base URL for Lambda functions
  QuarantineUserRoleArn:
    Type: String
    Description: ARN of the IAM role for quarantine user function
  FetchCloudLogsRoleArn:
    Type: String
    Description: ARN of the IAM role for fetch cloud logs function
  RemovePolicyRoleArn:
    Type: String
    Description: ARN of the IAM role for remove policy function
  ConfigureResourceAccessRoleArn:
    Type: String
    Description: ARN of the IAM role for configure resource access function
  CreateVolumeSnapshotsRoleArn:
    Type: String
    Description: ARN of the IAM role for create volume snapshots function
  DeleteVolumeSnapshotsRoleArn:
    Type: String
    Description: ARN of the IAM role for delete volume snapshots function
  QuarantineUserRoleName:
    Type: String
    Description: Name of the IAM role for quarantine user function
  FetchCloudLogsRoleName:
    Type: String
    Description: Name of the IAM role for fetch cloud logs function
  RemovePolicyRoleName:
    Type: String
    Description: Name of the IAM role for remove policy function
  ConfigureResourceAccessRoleName:
    Type: String
    Description: Name of the IAM role for configure resource access function
  CreateVolumeSnapshotsRoleName:
    Type: String
    Description: Name of the IAM role for create volume snapshots function
  DeleteVolumeSnapshotsRoleName:
    Type: String
    Description: Name of the IAM role for delete volume snapshots function

Resources:
  # CloudWatch Log Groups (Regional Resources)
  QuarantineUserLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ResourceName}-quarantine-user'
      RetentionInDays: 7

  FetchCloudLogsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ResourceName}-fetch-cloud-logs'
      RetentionInDays: 7

  RemovePolicyLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ResourceName}-remove-policy'
      RetentionInDays: 7

  ConfigureResourceAccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ResourceName}-configure-resource-access'
      RetentionInDays: 7

  CreateVolumeSnapshotsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ResourceName}-create-volume-snapshots'
      RetentionInDays: 7

  DeleteVolumeSnapshotsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ResourceName}-delete-volume-snapshots'
      RetentionInDays: 7

  # Lambda Functions (Regional Resources)
  QuarantineUserFunction:
    Type: AWS::Lambda::Function
    DependsOn: QuarantineUserLogGroup
    Properties:
      FunctionName: !Sub '${ResourceName}-quarantine-user'
      Runtime: python3.12
      Handler: app.index.handler
      Role: !Ref QuarantineUserRoleArn
      Code:
        S3Bucket: !Sub '${S3BucketPrefix}-${AWS::Region}'
        S3Key: quarantine_user.zip
      Timeout: 300
      MemorySize: 128
      Environment:
        Variables:
          API_BASE_URL: !Ref ApiBaseUrl
          DELEGATE_ROLE_NAME: !Ref QuarantineUserRoleName
      Tags:
        - Key: Name
          Value: !Sub '${ResourceName}-quarantine-user'
        - Key: 'sysdig.com/response-actions/cloud-actions'
          Value: 'true'

  FetchCloudLogsFunction:
    Type: AWS::Lambda::Function
    DependsOn: FetchCloudLogsLogGroup
    Properties:
      FunctionName: !Sub '${ResourceName}-fetch-cloud-logs'
      Runtime: python3.12
      Handler: app.index.handler
      Role: !Ref FetchCloudLogsRoleArn
      Code:
        S3Bucket: !Sub '${S3BucketPrefix}-${AWS::Region}'
        S3Key: fetch_cloud_logs.zip
      Timeout: 300
      MemorySize: 128
      Environment:
        Variables:
          API_BASE_URL: !Ref ApiBaseUrl
          DELEGATE_ROLE_NAME: !Ref FetchCloudLogsRoleName
      Tags:
        - Key: Name
          Value: !Sub '${ResourceName}-fetch-cloud-logs'
        - Key: 'sysdig.com/response-actions/cloud-actions'
          Value: 'true'

  RemovePolicyFunction:
    Type: AWS::Lambda::Function
    DependsOn: RemovePolicyLogGroup
    Properties:
      FunctionName: !Sub '${ResourceName}-remove-policy'
      Runtime: python3.12
      Handler: app.index.handler
      Role: !Ref RemovePolicyRoleArn
      Code:
        S3Bucket: !Sub '${S3BucketPrefix}-${AWS::Region}'
        S3Key: remove_policy.zip
      Timeout: 300
      MemorySize: 128
      Environment:
        Variables:
          API_BASE_URL: !Ref ApiBaseUrl
          DELEGATE_ROLE_NAME: !Ref RemovePolicyRoleName
      Tags:
        - Key: Name
          Value: !Sub '${ResourceName}-remove-policy'
        - Key: 'sysdig.com/response-actions/cloud-actions'
          Value: 'true'

  ConfigureResourceAccessFunction:
    Type: AWS::Lambda::Function
    DependsOn: ConfigureResourceAccessLogGroup
    Properties:
      FunctionName: !Sub '${ResourceName}-configure-resource-access'
      Runtime: python3.12
      Handler: app.index.handler
      Role: !Ref ConfigureResourceAccessRoleArn
      Code:
        S3Bucket: !Sub '${S3BucketPrefix}-${AWS::Region}'
        S3Key: configure_resource_access.zip
      Timeout: 300
      MemorySize: 128
      Environment:
        Variables:
          API_BASE_URL: !Ref ApiBaseUrl
          DELEGATE_ROLE_NAME: !Ref ConfigureResourceAccessRoleName
      Tags:
        - Key: Name
          Value: !Sub '${ResourceName}-configure-resource-access'
        - Key: 'sysdig.com/response-actions/cloud-actions'
          Value: 'true'

  CreateVolumeSnapshotsFunction:
    Type: AWS::Lambda::Function
    DependsOn: CreateVolumeSnapshotsLogGroup
    Properties:
      FunctionName: !Sub '${ResourceName}-create-volume-snapshots'
      Runtime: python3.12
      Handler: app.index.handler
      Role: !Ref CreateVolumeSnapshotsRoleArn
      Code:
        S3Bucket: !Sub '${S3BucketPrefix}-${AWS::Region}'
        S3Key: create_volume_snapshot.zip
      Timeout: 300
      MemorySize: 128
      Environment:
        Variables:
          API_BASE_URL: !Ref ApiBaseUrl
          DELEGATE_ROLE_NAME: !Ref CreateVolumeSnapshotsRoleName
      Tags:
        - Key: Name
          Value: !Sub '${ResourceName}-create-volume-snapshots'
        - Key: 'sysdig.com/response-actions/cloud-actions'
          Value: 'true'

  DeleteVolumeSnapshotsFunction:
    Type: AWS::Lambda::Function
    DependsOn: DeleteVolumeSnapshotsLogGroup
    Properties:
      FunctionName: !Sub '${ResourceName}-delete-volume-snapshots'
      Runtime: python3.12
      Handler: app.index.handler
      Role: !Ref DeleteVolumeSnapshotsRoleArn
      Code:
        S3Bucket: !Sub '${S3BucketPrefix}-${AWS::Region}'
        S3Key: delete_volume_snapshot.zip
      Timeout: 300
      MemorySize: 128
      Environment:
        Variables:
          API_BASE_URL: !Ref ApiBaseUrl
          DELEGATE_ROLE_NAME: !Ref DeleteVolumeSnapshotsRoleName
      Tags:
        - Key: Name
          Value: !Sub '${ResourceName}-delete-volume-snapshots'
        - Key: 'sysdig.com/response-actions/cloud-actions'
          Value: 'true'

Outputs:
  QuarantineUserFunctionArn:
    Value: !GetAtt QuarantineUserFunction.Arn
  FetchCloudLogsFunctionArn:
    Value: !GetAtt FetchCloudLogsFunction.Arn
  RemovePolicyFunctionArn:
    Value: !GetAtt RemovePolicyFunction.Arn
  ConfigureResourceAccessFunctionArn:
    Value: !GetAtt ConfigureResourceAccessFunction.Arn
  CreateVolumeSnapshotsFunctionArn:
    Value: !GetAtt CreateVolumeSnapshotsFunction.Arn
  DeleteVolumeSnapshotsFunctionArn:
    Value: !GetAtt DeleteVolumeSnapshotsFunction.Arn
